services:

  backend:
    build: .
    container_name: docpilot-container

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ./storage:/app/storage

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: docpilot-redis

    restart: unless-stopped
    
 

  worker:
    build: .
    container_name: docpilot-worker

    command: celery -A app.celery_app.celery worker --loglevel=info

    env_file:
      - .env

    depends_on:
      - redis

    volumes:
      - ./storage:/app/storage

    restart: unless-stopped

   